### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [kiel-live/transport-hub#1]
- [ ] UI
  - [ ] Show coverage map
  - [ ] List agencies / providers
  - [ ] Show agency routes
  - [ ] Show stops of a route
  - [ ] Show import errors
- [ ] Import
  - [ ] Prefix ids with some feed prefix / id
  - [ ] delete entries missing in newer data
  - [ ] Automate import task execution
  - [ ] Validate feed data
  - [x] Store import logs to db
  - [x] Import GTFS
  - [x] Import GBFS
  - [ ] Import GTFS-RT
- [ ] Api
  - [ ] streaming of updated data
